pipeline {
    agent { label "dev" }

    stages {

        stage("Clone") {
            steps {
                git url: "https://github.com/devashish-pandey/test-project.git",
                    branch: "main"
            }
        }

        stage("Build") {
            steps {
                sh 'docker build -t seogram:latest ./seogram-1.0.0'
            }
        }

        stage("Push") {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'hubCred',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {

                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker tag seogram:latest dextern001/seogram:latest'
                    sh 'docker push dextern001/seogram:latest'
                }
            }
        }

        stage("Deploy") {
            steps {
                dir("seogram-1.0.0") {
                    sh '''
                        docker compose pull
                        docker compose up -d
                    '''
                }
            }
        }
        post {
        success {
            emailext(
                subject:"Succesful build",
                body:"Good , succsess in build",
                to: 'pdevashish587@gmail.com'
                )
        }
        failure{
            emailext(
                subject:"failed build",
                body:"Bad , failure in build",
                to: 'pdevashish587@gmail.com'
                )
        }
    }
}
